Acrobot-v1:
  batch_size: 128
  buffer_size: 50000
  env_wrapper:
  - hrr_gym_wrappers.SSPObsWrapper:
      shape_out: 351
  exploration_final_eps: 0.1
  exploration_fraction: 0.12
  gamma: 0.99
  gradient_steps: -1
  learning_rate: 0.00063
  learning_starts: 0
  n_timesteps: 100000.0
  policy: MlpPolicy
  policy_kwargs: dict(net_arch=[256, 256])
  target_update_interval: 250
  train_freq: 4
  
CartPole-v1:
  batch_size: 64
  buffer_size: 100000
  env_wrapper:
  - hrr_gym_wrappers.SSPObsWrapper:
      shape_out: 251
  exploration_final_eps: 0.04
  exploration_fraction: 0.16
  gamma: 0.99
  gradient_steps: 128
  learning_rate: 0.0023
  learning_starts: 1000
  n_timesteps: 50000.0
  policy: MlpPolicy
  policy_kwargs: dict(net_arch=[256, 256])
  target_update_interval: 10
  train_freq: 256
  
LunarLander-v2:
  batch_size: 128
  buffer_size: 50000
  env_wrapper:
  - hrr_gym_wrappers.SSPObsWrapper:
      shape_out: 451
  exploration_final_eps: 0.1
  exploration_fraction: 0.12
  gamma: 0.99
  gradient_steps: -1
  learning_rate: 0.00063
  learning_starts: 0
  n_timesteps: 100000.0
  policy: MlpPolicy
  policy_kwargs: dict(net_arch=[256, 256])
  target_update_interval: 250
  train_freq: 4
  
MountainCar-v0:
  batch_size: 128
  buffer_size: 10000
  env_wrapper:
  - hrr_gym_wrappers.SSPObsWrapper:
      shape_out: 151
  exploration_final_eps: 0.07
  exploration_fraction: 0.2
  gamma: 0.98
  gradient_steps: 8
  learning_rate: 0.004
  learning_starts: 1000
  n_timesteps: 120000.0
  policy: MlpPolicy
  policy_kwargs: dict(net_arch=[256, 256])
  target_update_interval: 600
  train_freq: 16

maze-sample-5x5-v0: &maze-defaults
    env_wrapper:
    - hrr_gym_wrappers.SSPObsWrapper:
        shape_out: 151
        length_scale: 1
    n_timesteps: !!float 1.5e4
    policy: 'MlpPolicy'
    learning_rate: !!float 1e-3
    batch_size: 128
    buffer_size: 10000
    learning_starts: 0
    gamma: 0.99
    target_update_interval: 250
    train_freq: 4
    gradient_steps: -1
    exploration_fraction: 0.2
    exploration_final_eps: 0.01

maze-random-5x5-v0:
  <<: *maze-defaults
  
maze-random-6x6-v0:
  <<: *maze-defaults
  
maze-random-7x7-v0:
  <<: *maze-defaults
  n_timesteps: !!float 2e4
  
maze-random-8x8-v0:
  <<: *maze-defaults
  n_timesteps: !!float 2e4
  
maze-random-9x9-v0:
  <<: *maze-defaults
  n_timesteps: !!float 2.5e4
  
maze-random-10x10-v0:
  <<: *maze-defaults
  n_timesteps: !!float 2.5e4
  
maze-sample-10x10-v0:
  <<: *maze-defaults
  n_timesteps: !!float 2.5e4

maze-sample-25x25-v0:
  <<: *maze-defaults
  n_timesteps: !!float 5e4
  
maze-sample-50x50-v0:
  <<: *maze-defaults
  n_timesteps: !!float 1e5
  
maze-sample-100x100-v0:
  <<: *maze-defaults
  n_timesteps: !!float 1e5
  
