Acrobot-v1:
  batch_size: 8
  clip_range: 0.3
  ent_coef: 0.0016887662574405905
  gae_lambda: 0.98
  gamma: 0.98
  learning_rate: 0.0014122296715315709
  max_grad_norm: 0.8
  n_envs: 16
  n_epochs: 1
  n_steps: 32
  n_timesteps: 1000000.0
  normalize: true
  policy: MlpPolicy
  policy_kwargs: dict(net_arch=dict(pi=[64, 64], vf=[64, 64]),activation_fn=nn.ReLU,ortho_init=False,features_extractor_class=hrr_gym_wrappers.SSPProcesser,features_extractor_kwargs=dict(features_dim=225,ssp_h=[0.028142760643669197,
    16.769420234485487, 1.1949794271332383, 0.19860115953574767, 0.11197384800365881,
    0.3108735565198609]))
  vf_coef: 0.19001510460449456
CartPole-v1:
  batch_size: 256
  clip_range: lin_0.2
  ent_coef: 0.0
  gae_lambda: 0.8
  gamma: 0.98
  learning_rate: lin_0.001
  n_envs: 8
  n_epochs: 20
  n_steps: 32
  n_timesteps: 100000.0
  policy: MlpPolicy
  policy_kwargs: dict(net_arch=dict(pi=[64], vf=[64]),activation_fn=nn.ReLU,features_extractor_class=hrr_gym_wrappers.SSPProcesser,features_extractor_kwargs=dict(features_dim=251,ssp_h=[0.96000004,
    0.1, 0.083775806, 0.1]))
LunarLander-v2:
  batch_size: 64
  ent_coef: 0.01
  gae_lambda: 0.98
  gamma: 0.999
  n_envs: 16
  n_epochs: 4
  n_steps: 1024
  n_timesteps: 1000000.0
  policy: MlpPolicy
  policy_kwargs: dict(net_arch=dict(pi=[64], vf=[64]),activation_fn=nn.ReLU,features_extractor_class=hrr_gym_wrappers.SSPProcesser,features_extractor_kwargs=dict(features_dim=451))
LunarLanderContinuous-v2:
  batch_size: 64
  ent_coef: 0.01
  gae_lambda: 0.98
  gamma: 0.999
  n_envs: 16
  n_epochs: 4
  n_steps: 1024
  n_timesteps: 1000000.0
  policy: MlpPolicy
  policy_kwargs: dict(net_arch=dict(pi=[64], vf=[64]),activation_fn=nn.ReLU,features_extractor_class=hrr_gym_wrappers.SSPProcesser,features_extractor_kwargs=dict(features_dim=451))
MountainCar-v0:
  ent_coef: 0.0
  gae_lambda: 0.98
  gamma: 0.99
  n_envs: 16
  n_epochs: 4
  n_steps: 16
  n_timesteps: 1000000.0
  policy: MlpPolicy
  policy_kwargs: ',features_extractor_class=hrr_gym_wrappers.SSPProcesser,features_extractor_kwargs=dict(features_dim=151,ssp_h=[0.34728204118474704,
    0.15569961421392498]))'
MountainCarContinuous-v0:
  batch_size: 256
  clip_range: 0.1
  ent_coef: 0.00429
  gae_lambda: 0.9
  gamma: 0.9999
  learning_rate: 7.77e-05
  max_grad_norm: 5
  n_envs: 1
  n_epochs: 10
  n_steps: 8
  n_timesteps: 20000.0
  normalize: true
  policy: MlpPolicy
  policy_kwargs: dict(log_std_init=-3.29, ortho_init=False,features_extractor_class=hrr_gym_wrappers.SSPProcesser,features_extractor_kwargs=dict(features_dim=151))
  use_sde: true
  vf_coef: 0.19
Pendulum-v1:
  clip_range: 0.2
  ent_coef: 0.0
  gae_lambda: 0.95
  gamma: 0.9
  learning_rate: 0.001
  n_envs: 4
  n_epochs: 10
  n_steps: 1024
  n_timesteps: 100000.0
  policy: MlpPolicy
  policy_kwargs: dict(net_arch=dict(pi=[64], vf=[64]),activation_fn=nn.ReLU,features_extractor_class=hrr_gym_wrappers.SSPProcesser,features_extractor_kwargs=dict(features_dim=73,ssp_h=[0.23239569118125408,
    1.451069567569478, 1.1845291313041482]))
  sde_sample_freq: 4
  use_sde: true
