LunarLanderContinuous-v2:
  batch_size: 256
  buffer_size: 1000000
  ent_coef: auto
  gamma: 0.99
  gradient_steps: 1
  learning_rate: lin_7.3e-4
  learning_starts: 10000
  n_timesteps: 500000.0
  policy: MlpPolicy
  policy_kwargs: dict(net_arch=[400, 300],features_extractor_class=hrr_gym_wrappers.SSPProcesser,features_extractor_kwargs=dict(features_dim=451)
  tau: 0.01
  train_freq: 1
MountainCarContinuous-v0:
  batch_size: 512
  buffer_size: 50000
  ent_coef: 0.1
  gamma: 0.9999
  gradient_steps: 32
  learning_rate: 0.0003
  learning_starts: 0
  n_timesteps: 50000.0
  policy: MlpPolicy
  policy_kwargs: dict(log_std_init=-3.67, net_arch=[64, 64],features_extractor_class=hrr_gym_wrappers.SSPProcesser,features_extractor_kwargs=dict(features_dim=151,ssp_h=[0.34728204118474704,
    0.15569961421392498])
  tau: 0.01
  train_freq: 32
  use_sde: true
Pendulum-v1:
  learning_rate: 0.001
  n_timesteps: 20000
  policy: MlpPolicy
  policy_kwargs: ',features_extractor_class=hrr_gym_wrappers.SSPProcesser,features_extractor_kwargs=dict(features_dim=201)'


# === Bullet envs ===

# Tuned
HalfCheetahBulletEnv-v0: &pybullet-defaults
  # env_wrapper:
  #   - sb3_contrib.common.wrappers.TimeFeatureWrapper
  #   - rl_zoo3.wrappers.DelayedRewardWrapper:
  #       delay: 10
  #   - rl_zoo3.wrappers.HistoryWrapper:
  #       horizon: 10
  n_timesteps: !!float 1e6
  policy: 'MlpPolicy'
  learning_rate: !!float 7.3e-4
  buffer_size: 300000
  batch_size: 256
  ent_coef: 'auto'
  gamma: 0.98
  tau: 0.02
  train_freq: 8
  gradient_steps: 8
  learning_starts: 10000
  # replay_buffer_kwargs: "dict(handle_timeout_termination=True)"
  use_sde: True
  policy_kwargs: "dict(log_std_init=-3, net_arch=[400, 300], features_extractor_class=hrr_gym_wrappers.SSPProcesser,features_extractor_kwargs=dict(features_dim=1001))"

# Tuned
AntBulletEnv-v0:
  <<: *pybullet-defaults

HopperBulletEnv-v0:
  <<: *pybullet-defaults
  learning_rate: lin_7.3e-4

Walker2DBulletEnv-v0:
  <<: *pybullet-defaults
  learning_rate: lin_7.3e-4
  
# Tuned
ReacherBulletEnv-v0:
  <<: *pybullet-defaults
  n_timesteps: !!float 3e5