Ant-v4:
  learning_starts: 10000
  n_timesteps: 1000000.0
  policy: MlpPolicy
  policy_kwargs: dict(features_extractor_class=hrr_gym_wrappers.SSPProcesser,features_extractor_kwargs=dict(features_dim=501,basis_type="rand"))
HalfCheetah-v4:
  learning_starts: 10000
  n_timesteps: 1000000.0
  policy: MlpPolicy
  policy_kwargs: dict(features_extractor_class=hrr_gym_wrappers.SSPProcesser,features_extractor_kwargs=dict(features_dim=501,basis_type="rand"))
Hopper-v4:
  learning_starts: 10000
  n_timesteps: 1000000.0
  policy: MlpPolicy
  policy_kwargs: dict(features_extractor_class=hrr_gym_wrappers.SSPProcesser,features_extractor_kwargs=dict(features_dim=501,basis_type="rand"))
  top_quantiles_to_drop_per_net: 5
LunarLanderContinuous-v2:
  batch_size: 256
  buffer_size: 1000000
  ent_coef: auto
  gamma: 0.99
  gradient_steps: 1
  learning_rate: lin_7.3e-4
  learning_starts: 10000
  n_timesteps: 500000.0
  policy: MlpPolicy
  policy_kwargs: dict(net_arch=[400, 300],features_extractor_class=hrr_gym_wrappers.SSPProcesser,features_extractor_kwargs=dict(features_dim=451))
  tau: 0.01
  train_freq: 1
MountainCarContinuous-v0:
  batch_size: 512
  buffer_size: 50000
  ent_coef: 0.1
  gamma: 0.9999
  gradient_steps: 32
  learning_rate: 0.0003
  learning_starts: 0
  n_timesteps: 50000.0
  policy: MlpPolicy
  policy_kwargs: dict(log_std_init=-3.67, net_arch=[64, 64],features_extractor_class=hrr_gym_wrappers.SSPProcesser,features_extractor_kwargs=dict(features_dim=151))
  tau: 0.01
  train_freq: 32
  use_sde: true
Pendulum-v1:
  learning_rate: 0.001
  n_timesteps: 20000
  policy: MlpPolicy
  policy_kwargs: dict(features_extractor_class=hrr_gym_wrappers.SSPProcesser,features_extractor_kwargs=dict(features_dim=201))
Swimmer-v4:
  gamma: 0.9999
  learning_starts: 10000
  n_timesteps: 1000000.0
  policy: MlpPolicy
  policy_kwargs: dict(features_extractor_class=hrr_gym_wrappers.SSPProcesser,features_extractor_kwargs=dict(features_dim=501,basis_type="rand"))
Walker2d-v4:
  learning_starts: 10000
  n_timesteps: 1000000.0
  policy: MlpPolicy
  policy_kwargs: dict(features_extractor_class=hrr_gym_wrappers.SSPProcesser,features_extractor_kwargs=dict(features_dim=501,basis_type="rand"))
